sudo: false
language: python
services:
  - mysql
addons:
  apt:
    packages:
    - python-dev
matrix:
  fast_finish: true
  allow_failures:
  - python: "nightly"
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - "pip install MySQL-python"
  - "pip install ."
  - "pip install -r developer_requirements.txt"
  - "pip install coveralls"
before_script:
  - mysql -e 'create database haralyzer_api_test;'
script: py.test --cov har_api tests/
after_success:
  - coveralls
