sudo: false
language: python
matrix:
  fast_finish: true
  allow_failures:
  - python: "nightly"
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - "pip install ."
  - "pip install -r developer_requirements.txt"
script: py.test --cov har_api tests/
