"""Adding page.url

Revision ID: 189abb6a498b
Revises: 3f798d8f725b
Create Date: 2015-07-27 13:06:23.408592

"""

# revision identifiers, used by Alembic.
revision = '189abb6a498b'
down_revision = '3f798d8f725b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('url', sa.String(length=256), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'url')
    ### end Alembic commands ###
